version: "3.9"
services:
  container1:
    image: nginx:1.23
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: host
    networks:
      - network1  # container1 is running in network1 created by user.
  container2:     # container2 is runnung on default network created by system.
    image: httpd:2.4
    ports:
      - target : 80
        published: 8081
        protocol: tcp
        mode: host
networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24