version: "3.9"
services:
  container1:
    image: nginx:1.23
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: host
  container2:
    image: httpd:2.4
    ports:
      - target : 80
        published: 8081
        protocol: tcp
        mode: host
   