pipeline{
    agent { label 'dock'}
    triggers { pollSCM('* * * * *')}
   stages{
        stage ('clone'){
            steps{
                git branch :'master',
                 url : 'https://github.com/DevProjectsForDevOps/StudentCoursesRestAPI.git'
            }
        }
        stage ('container operations'){
            steps{
                sh """
                 cd studentcourse_khajasir
                 docker image build -t studentcourserest:1.0 .
                 docker container run -d --name container1 -P studentcourserest:1.0 

                 """
            }
        }

    }
}
